[package]
name = "moji_odpadki_parser"
version = "0.1.3"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", default-features = false, features = ["serde_derive", "alloc"] }

[features]
default = ["alloc"]
alloc = []
std = ["alloc"]
